// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type CliNote struct {
	ID        int64
	Command   string
	Note      string
	CreatedAt sql.NullTime
}
